formatter: markdown table
sections:
  hide-all: true
  show:
  - inputs
  - outputs
  - requirements
  - resources
  - data-sources
  - modules

sort:
  enabled: true
  by: required
settings:
  indent: 3


recursive:
  enabled: true
  path: .

content: ""
