variable "powershell_task_name"  {default = "null"}
variable "powershell_task_window_id"  {default = "null"}
variable "powershell_task_priority" { default = "null"}
variable "service_role_arn" {default = "null"}
variable "max_concurrency"  {default = "null"}
variable "max_errors" {default = "null"}
variable "powershell_task_window_target_id"  {default = "null"}
variable "timeout_seconds" {default = "null"}
variable "powershell_task" {default = 600}
