name: Terraform Module Releaser
on:
  pull_request:
    types: [opened, reopened, synchronize, closed] # Closed required
    branches:
      - main

permissions:
  contents: write # Required for to push tags, create release, and push changes to the wiki
  pull-requests: write # Required to comment on pull request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Module Releaser
        uses: techpivot/terraform-module-releaser@v1
        with:
          # Enhanced commit message keywords for better versioning
          major-keywords: "major,breaking change,BREAKING"
          minor-keywords: "feat,feature,add,new"
          patch-keywords: "fix,bug,patch,update,chore,docs,refactor"
          
          # Documentation and versioning settings
          default-first-tag: "v1.0.0"
          terraform-docs-version: "v0.20.0"
          
          # Cleanup and maintenance
          delete-legacy-tags: true
          
          # Wiki configuration
          disable-wiki: false
          wiki-sidebar-changelog-max: 10
          
          # File patterns for better module management
          module-path-ignore: "**/examples/**,**/test/**,**/tests/**,.github/**"
          module-change-exclude-patterns: ".gitignore,*.md,*.tftest.hcl,tests/**,examples/**,docs/**"
          module-asset-exclude-patterns: ".gitignore,*.md,*.tftest.hcl,tests/**,examples/**,docs/**,*.tfvars.example"