name: Terraform Module Releaser
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for tag history

      - uses: techpivot/terraform-module-releaser@pull/217/head
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete-legacy-tags: false
          major-keywords: major,breaking change,BREAKING
          minor-keywords: feat, feature, add, new
          patch-keywords: fix,bug, patch, update, chore, docs, refactor
          use-ssh-source-format: true
