name: Terraform Module Releaser

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Module Releaser
        uses: techpivot/terraform-module-releaser@v1
        with:
          major-keywords: major,breaking change,BREAKING
          minor-keywords: feat,feature,add,new
          patch-keywords: fix,bug,patch,update,chore,docs,refactor
          default-first-tag: v1.0.0
          terraform-docs-version: v0.20.0
          delete-legacy-tags: false
          disable-wiki: false
          wiki-sidebar-changelog-max: 3
          module-change-exclude-patterns: .gitignore,*.md,*.txt,LICENSE,docs/**,examples/**,*.tftest.hcl,tests/**
          module-asset-exclude-patterns: .gitignore,*.md,*.txt,LICENSE,*.tftest.hcl,tests/**
          use-ssh-source-format: true
    